permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: "http://cwlseu.github.io"  
cdn_url: 7u2t01.com1.z0.glb.clouddn.com
lsi: false
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"
timezone: Asia/Beijing

# Title
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "cwlseu"
      
# Site settings
title: Clython
header-img: "img/autumn.jpg"
tagline: "hello"  
description: "用代码代替野心飞翔，加油"  
# About/contact
owner: 
  name: "cwlseu"
  email: cwlseu@qq.com
  bio: "长空破浪会有时，直挂云帆济沧海"

# Data
favicon: img/favicon.ico


# Analytics and webmaster tools stuff goes here
google_analytics: UA-86501439-1
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here